spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.132.161:3306/sharenotes_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/sharenotes_dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: sharenotes_dev
    password: YwbTrt5C8LFxXXbm
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
#        jdbc:
        #batch save/update
#          batch_size: 500
#          batch_versioned_data: true
#        order_inserts: true
#        order_updates: true
#        ddl-auto: update
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true